### ISSUE TITLE
Please release a new version?

### ISSUE THREAD

**Issue by JounQin** [unplugin/unplugin-vue-complex-types#26]
### Describe the bug

<img width="581" alt="image" src="https://github.com/unplugin/unplugin-vue-complex-types/assets/8336744/80e56636-fb14-4981-aee2-f92ee7a9242a">

### Reproduction

unnecessary

### System Info

```Shell
N/A
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by so1ve** [comment]
Released `v0.2.0`
